Added the Blazor Viewer
RHEAGROUP/COMET-WEB-Community-Edition pull request #176
Opened 2022-10-13 14:34 UTC by jaimeatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
The Viewer developed in Blazor has been included in COMET-WEB-Community-Edition

2022-10-14 11:18 UTC, samatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +
I propose you put a `//TODO:` statement here to make it explicit what you intend to code here.

2022-10-14 11:18 UTC, samatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +
I propose you put a `//TODO:` statement here to make it explicit what you intend to code here.

2022-10-14 11:18 UTC, samatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +
I propose you put a `//TODO:` statement here to make it explicit what you intend to code here.

2022-10-14 11:18 UTC, samatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +
I propose you put a `//TODO:` statement here to make it explicit what you intend to code here.

2022-10-14 11:18 UTC, samatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +
I propose you put a `//TODO:` statement here to make it explicit what you intend to code here.

2022-10-14 11:18 UTC, samatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +}
add new line at the end of file

2022-10-14 11:20 UTC, samatrhea commented on COMETwebapp/Primitives/Cone.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:20 UTC, samatrhea commented on COMETwebapp/Primitives/Cube.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:20 UTC, samatrhea commented on COMETwebapp/Primitives/CustomPrimitive.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:21 UTC, samatrhea commented on COMETwebapp/Primitives/CustomPrimitive.cs
> +}
add new line at the end

2022-10-14 11:21 UTC, samatrhea commented on COMETwebapp/Primitives/Cylinder.cs
> +//    Copyright (c) 2022 RHEA System S.A.
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:21 UTC, samatrhea commented on COMETwebapp/Primitives/Cylinder.cs
> +}
add new line

2022-10-14 11:22 UTC, samatrhea commented on COMETwebapp/Primitives/Line.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:22 UTC, samatrhea commented on COMETwebapp/Primitives/PositionablePrimitives.cs
> +    public abstract class PositionablePrimitives : Primitive
please add XML docs

2022-10-14 11:22 UTC, samatrhea commented on COMETwebapp/Primitives/PositionablePrimitives.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:22 UTC, samatrhea commented on COMETwebapp/Primitives/Primitive.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:23 UTC, samatrhea commented on COMETwebapp/Primitives/Sphere.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:23 UTC, samatrhea commented on COMETwebapp/Primitives/Torus.cs
> +//    Author: Jaime Bernar
please add: , Sam Gerené, Alex Vorobiev, Alexander van Delft

2022-10-14 11:24 UTC, samatrhea commented on COMETwebapp/Scene.cs
> +        /// Collection of temporaty <see cref="Primitive"/> in the Scene.
spellong -> temporaty: temporary

2022-10-14 11:24 UTC, samatrhea commented on COMETwebapp/Scene.cs
> +    /// Static class to acess the resources of a Scene
spelling `access`

2022-10-14 11:24 UTC, samatrhea commented on COMETwebapp/Scene.cs
> +    using COMETwebapp.Primitives;
please reorder using statements according to convention

2022-10-14 11:25 UTC, samatrhea commented on COMETwebapp/wwwroot/Scripts/Helper.js
> +﻿function CreateMaterial(diffuse, specular, emissive, ambient, materialName, scene) {
please add copyright header and document the methods

2022-10-14 11:26 UTC, samatrhea commented on COMETwebapp/wwwroot/Scripts/babylonInterop.js
> +﻿"use strict";
please add copyright header and document the methods

2022-10-14 13:09 UTC, jaimeatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +        protected async override Task OnAfterRenderAsync(bool firstRender)
@samatrhea Can you explain me what do you mean?

2022-10-14 13:12 UTC, alexatrhea commented on COMETwebapp/Components/Viewer/BabylonCanvasBase.cs
> +        protected async override Task OnAfterRenderAsync(bool firstRender)
all code, like this method here should have documentation above it:

```
/// <summary>
/// ...
/// </summary>
```
etc

2022-10-15 21:30 UTC, samatrhea requested changes

2022-10-15 21:30 UTC, samatrhea commented on COMETwebapp/wwwroot/Scripts/babylonInterop.js
> +/// <summary>
please use javascript documentation style:

https://www.valentinog.com/blog/jsdoc/

2022-10-15 21:30 UTC, samatrhea commented on tatic Dictionarystring, Primitive temporaryPrimitivesCollection = new Dictionarystring, Primitive();
> +[33mc85bb2e[m[33m ([m[1;36mHEAD -> [m[1;32mfeat/GH159-Merge-BlazorViewer-COMET-WEB[m[33m, [m[1;31morigin/feat/GH159-Merge-BlazorViewer-COMET-WEB[m[33m)[m Added the Blazor Viewer; fixes
I don;t think this file needs to be in the code-base

2022-10-20 11:14 UTC, samatrhea approved these changes

2022-10-20 11:26 UTC, merged