Add Warning Window, Add Filters on Tree, Refactor ViewerPage
RHEAGROUP/COMET-WEB-Community-Edition pull request #229
Opened 2023-01-19 11:50 UTC by jaimeatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
A warning window for when the user selects a new primitive before submiting data its added. 
Add filters on the product tree.
Refactoring on the viewer page

2023-01-20 09:44 UTC, antoineatrhea requested changes
Small remarks

2023-01-20 09:44 UTC, antoineatrhea commented on COMETwebapp/Components/Canvas/ActualFiniteStateSelectorComponent.razor.cs
> +// <copyright file="StateSelector.razor.cs" company="RHEA System S.A.">
The copyright filename is not aligned with the current filename. 
General remarks, the copyright year can move to 2023 no?

2023-01-20 09:44 UTC, antoineatrhea commented on COMETwebapp/Components/Canvas/ProductTree.razor.cs
> +
Missing class documentation

2023-01-24 08:33 UTC, antoineatrhea approved these changes

2023-01-24 08:38 UTC, alexatrhea approved these changes

2023-01-24 08:42 UTC, merged

2023-01-24 08:43 UTC, lxatrhea approved these changes