Change the order the Scene is computed
RHEAGROUP/COMET-WEB-Community-Edition pull request #243
Opened 2023-01-25 11:18 UTC by jaimeatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
the tree is computed before the scene and then the scene it's computed based on the results of the tree.

2023-01-25 13:22 UTC, antoineatrhea requested changes
Minor change

2023-01-25 13:22 UTC, antoineatrhea commented on COMETwebapp/Model/SceneObject.cs
> +            //var sceneObject = Create(this.ElementBase, this.Option, this.States);
Remove this commented code

2023-02-03 08:46 UTC, lxatrhea approved these changes

2023-02-06 09:02 UTC, lxatrhea approved these changes

2023-02-06 09:05 UTC, merged