Create parameter table + add devexpress; fixes #16
RHEAGROUP/COMET-WEB-Community-Edition pull request #26
Opened 2022-04-26 11:00 UTC by justineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
- Create a first version for the parameter table with DevExpress components.
- Add DevExpress tool in the application : because of conflicts between css files, I had to recreate the application from scratch with the tool. The functionalities are the same but the design is changed.

2022-04-27 07:18 UTC, alexatrhea approved these changes

2022-04-29 08:59 UTC, lxatrhea requested changes

2022-04-29 08:59 UTC, lxatrhea commented on COMETwebapp/COMETwebapp/Components/OpenModel.razor
> +    public class ModelDto
I think it is good practice for every class to reside in it's own .cs file so it is reusable.
On the other hand, do you really need a separate class? Not just 3 variables?
You define a ModelDto (sounds pretty generic, maybe even too generic) that has 3 properties that all start with the text "Selected".
So to me it looks like a generic class, that has very context-specific properties. 

I think you should think about making the ModelDto class more specific to the situation, or move the properties from ModelDto to the @code level.

I also think that it is not a DTO, or am I missing something here?
We use the term DTO for objects used to transfer data to an from a database.

2022-04-29 08:59 UTC, lxatrhea commented on COMETwebapp/COMETwebapp/Model/MyParameter.cs
> +    public class MyParameter
Very generic name!!

2022-04-29 10:30 UTC, lxatrhea approved these changes

2022-04-29 11:52 UTC, closed without merging