User management : Fix #266 #267
RHEAGROUP/COMET-WEB-Community-Edition pull request #277
Opened 2023-02-22 14:34 UTC by nabilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fix #266 #267 

Feature :
- A user can see all available users
- Filter, sort and search users
- Create or deprecate a user

2023-02-22 15:07 UTC, samatrhea requested changes

2023-02-22 15:07 UTC, samatrhea commented on COMETwebapp/SessionManagement/ISessionAnchor.cs
> +        /// <summary>
i don;t think we need to create all these methods on the the ISessionAnchor for each kind of thing we want to query from the cache that is encapsulated ny the ISession interface. Please just get the data from the ISession provided by the SDK and do that in the ViewModel

2023-02-22 15:07 UTC, samatrhea commented on COMETwebapp/ViewModels/Pages/UserManagement/UserManagementPageViewModel.cs
> +        public async Task Grid_ModelSaving()
please remove the word `Grid`, this is a viewmodel and the fact we are using a Grid control is not relevant. If tomorrwo we decide we don;t want to use a grid but a list or something else altogether then this method name is no longer valid.

2023-02-22 15:07 UTC, samatrhea commented on COMETwebapp/ViewModels/Pages/UserManagement/UserManagementPageViewModel.cs
> +            this.AvailableOrganizations = this.SessionAnchor.GetAvailableOrganizations();
please do not use the intermediate ISEssionAnchor interface, just use the ISession directly

2023-02-22 15:07 UTC, samatrhea commented on COMETwebapp/ViewModels/Pages/UserManagement/UserManagementPageViewModel.cs
> +            this.DataSource.AddRange(this.SessionAnchor.GetPersons());
adding the created user should happen based on a message coming from the messagebus, please have a look at COMET-IME how this is done. When use the messagebased approach then also persons added by another using in another instance of running web-app or the desktop app will appear as well on a refresh.

2023-02-22 15:36 UTC, nabilatrhea commented on COMETwebapp/ViewModels/Pages/UserManagement/UserManagementPageViewModel.cs
> +        public Person Person { get; set; } = new();
you think i should bind the new user data directly in the component ?

2023-02-23 14:33 UTC, lxatrhea approved these changes

2023-03-03 09:49 UTC, lxatrhea approved these changes

2023-03-03 09:52 UTC, antoineatrhea approved these changes

2023-03-03 09:54 UTC, merged