Multiple value selection for enumeration : Fix #282
RHEAGROUP/COMET-WEB-Community-Edition pull request #311
Opened 2023-03-21 09:02 UTC by nabilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fix #282 
For EnumerationParameterType that allows multi-selection :
- The UI shows a dropdown component with a ListBox to select multiple elements
- Write selected values to database

2023-03-21 16:28 UTC, jaimeatrhea approved these changes

2023-03-22 07:45 UTC, antoineatrhea requested changes
Small changes requested

2023-03-22 07:45 UTC, antoineatrhea commented on COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/EnumerationParameterTypeEditorViewModelTestFixture.cs
> +                Assert.That(async () => this.viewModel.OnConfirmButtonClick(), Throws.Nothing);
please await the method

2023-03-22 07:45 UTC, antoineatrhea commented on COMETwebapp/Components/Shared/ParameterTypeEditors/EnumerationParameterTypeEditor.razor.cs
> +                this.Disposables.Add(vm.WhenAnyValue(x => x.IsOnEditMode)
please combine those registration

2023-03-22 07:45 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/IEnumerationParameterTypeEditorViewModel.cs
> +    public interface IEnumerationParameterTypeEditorViewModel
Missing documentation

2023-03-22 09:21 UTC, antoineatrhea approved these changes

2023-03-22 09:24 UTC, merged