Behaviour of ParameterTable changed: Fix #312
RHEAGROUP/COMET-WEB-Community-Edition pull request #313
Opened 2023-03-23 11:12 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #312 

- Filter on ActualFiniteState removed
- Grouping by Parameter and Option removed
- Max-Height set to scroll into table instead of into page
- Special button to update the valueSwitch

#### ValueSwitch Demo
##### ReadOnly state
The update button is disabled if the user is not allowed to edit the Parameter or if the current value of ParameterValueSwitch is the same of the ValueSwitch of the ParameterValueSet.
![image](https://user-images.githubusercontent.com/97221392/227184487-e25ee353-1053-4edf-bdd5-4c06472fb0cf.png)
*button disabled*
![image](https://user-images.githubusercontent.com/97221392/227185581-d74431e0-7df8-4688-8773-1d64a5c6405d.png)
*button enabled*

##### Highlight
The ValueSwitch of the ParameterValueSet is highlighted while selecting the ParameterValueSwitch 
![image](https://user-images.githubusercontent.com/97221392/227186426-49f961c4-d86d-468f-ba37-c2d9db33876c.png)

2023-03-23 12:40 UTC, jaimeatrhea approved these changes

2023-03-24 11:31 UTC, samatrhea requested changes

2023-03-24 11:31 UTC, samatrhea commented on COMETwebapp/ViewModels/Components/Shared/Selectors/ParameterSwitchKindSelectorViewModel.cs
> +            set
this is a bit of an ani-pattern. I prefer we do not have extra logic in the getters/setters

2023-03-24 12:23 UTC, samatrhea approved these changes

2023-03-24 12:31 UTC, merged