Validation of parameters in element usage : Fix #199
RHEAGROUP/COMET-WEB-Community-Edition pull request #316
Opened 2023-03-28 13:27 UTC by nabilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fix #199 

- Provide feedback to user when the new field is incorrect
- Add validation to the 3D viewer properties

2023-03-28 13:35 UTC, antoineatrhea requested changes
General comment : Could you make the Validation a special method, created inside the ParameterTypeEditorBaseVM ? Like "IsValid" and include that IsValid in the if statement? So you don't duplicate code on each VM

2023-03-28 15:03 UTC, antoineatrhea requested changes
indentation problem and some references could be removed

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/Components/Shared/ParameterTypeEditors/BooleanParameterTypeEditor.razor
> +    if (!string.IsNullOrEmpty(this.ViewModel.ValidationMessage))
You could keep a special component to display the error message

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/DateParameterTypeEditorViewModel.cs
> +    using DynamicData;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/DateTimeParameterTypeEditorViewModel.cs
> +    using DynamicData;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/EnumerationParameterTypeEditorViewModel.cs
> +    using DynamicData;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/IParameterEditorBaseViewModel.cs
> +		///     The validation messages to display
weird indentation

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorBaseViewModel.cs
> +		///     The validation messages to display
Weird identation

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorBaseViewModel.cs
> +
remove this blank line

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/QuantityKindParameterTypeEditorViewModel.cs
> +    using DynamicData;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/TextParameterTypeEditorViewModel.cs
> +    using DynamicData;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/TimeOfDayParameterTypeEditorViewModel.cs
> +    using DynamicData;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/BooleanParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/DateParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/DateTimeParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/EnumerationParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/QuantityKindParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/TextParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:03 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Shared/ParameterTypeEditors/TimeOfDayParameterTypeEditorTestFixture.cs
> +    using COMETwebapp.ViewModels.Components.Shared;
is the reference still needed?

2023-03-28 15:10 UTC, antoineatrhea commented on COMETwebapp/Components/Shared/ParameterTypeEditors/BooleanParameterTypeEditor.razor
> +    if (!string.IsNullOrEmpty(this.ViewModel.ValidationMessage))
What I meant here is that your component was relevant, but use only a string as parameter instead of a VM has previously

2023-03-29 06:45 UTC, antoineatrhea requested changes
Minor things, when done, I approve

2023-03-29 06:45 UTC, antoineatrhea commented on COMETwebapp/Components/Shared/ValidationMessageComponent.razor
> +@inherits DisposableComponent
Why does it inherits DisposableComponent?

2023-03-29 06:45 UTC, antoineatrhea commented on COMETwebapp/Components/Shared/ValidationMessageComponent.razor.cs
> +}
missing EOF

2023-03-29 06:45 UTC, antoineatrhea commented on COMETwebapp/Components/Shared/ValidationMessageComponent.razor
> +}
Missing EOF

2023-03-29 06:45 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorBaseViewModel.cs
> +        public bool AreChangesValid(object value) {
Please put the '{' on the next line

2023-03-29 07:37 UTC, jaimeatrhea requested changes

2023-03-29 07:37 UTC, jaimeatrhea commented on COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorSelectorViewModelTestFixture.cs
> +            Assert.That(async () => await booleanParameterEditor.OnParameterValueChanged("test"), Throws.Nothing);
Can you add the new asserts in the Assert.Multiple block?

2023-03-29 07:37 UTC, jaimeatrhea commented on COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorSelectorViewModelTestFixture.cs
> +            Assert.That(async () => await dateParameterEditor.OnParameterValueChanged("test"), Throws.Nothing);
Same as before

2023-03-29 07:37 UTC, jaimeatrhea commented on COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorSelectorViewModelTestFixture.cs
> +            Assert.That(async () => await enumerationParameterEditor.OnParameterValueChanged("test"), Throws.Nothing);
Same as before

2023-03-29 07:37 UTC, jaimeatrhea commented on COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorSelectorViewModelTestFixture.cs
> +            Assert.That(async () => await textParameterEditor.OnParameterValueChanged(5), Throws.Nothing);
Same as before

2023-03-29 07:37 UTC, jaimeatrhea commented on COMETwebapp.Tests/ViewModels/Components/Shared/ParameterEditors/ParameterTypeEditorSelectorViewModelTestFixture.cs
> +            Assert.That(async () => await quantityKindEditor.OnParameterValueChanged("test"), Throws.Nothing);
Same as before

2023-03-29 08:38 UTC, antoineatrhea approved these changes

2023-03-29 08:39 UTC, merged