Terminal Common library created: Fix #317
RHEAGROUP/COMET-WEB-Community-Edition pull request #322
Opened 2023-03-31 10:00 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #317

- Common library created
- Header file of moved files updated to follow the new license

2023-04-04 08:08 UTC, jaimeatrhea commented on COMET.Web.Common/Services/NotificationService/NotificationService.cs
> +        public void RemoveNotifications(int amount)
Hmmm not sure of this. I don't like that the user needs to specify a negative number... The name of the method suggest that the amount is removed... Also, if you put a negative number the value is not removed but added.

2023-04-04 08:19 UTC, jaimeatrhea approved these changes

2023-04-14 07:13 UTC, samatrhea requested changes

2023-04-14 07:13 UTC, samatrhea commented on COMETwebapp/wwwroot/Skybox/License.txt
> +//    Authors: Sam Geren�, Alex Vorobiev, Alexander van Delft, Jaime Bernar
please add more names

2023-04-14 08:07 UTC, samatrhea approved these changes

2023-04-14 08:11 UTC, merged