System representation common component and url update : Fix #307
RHEAGROUP/COMET-WEB-Community-Edition pull request #337
Opened 2023-04-18 09:50 UTC by nabilatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #307 
- The SystemRepresentation uses common components created for filtering. 
- When selecting option filter, the selection is reflected inside the URL

2023-04-18 11:39 UTC, antoineatrhea requested changes
Small changes requested

2023-04-18 11:39 UTC, antoineatrhea commented on COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor.cs
> +                additionalParameters["option"] = this.ViewModel.OptionSelector.SelectedOption.Iid.ToString();
use the QueryKeys.OptionKey value

2023-04-18 11:39 UTC, antoineatrhea commented on COMETwebapp/Components/SystemRepresentation/SystemRepresentationBody.razor.cs
> +
remove additional break line

2023-04-18 11:39 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/SystemRepresentation/SystemRepresentationBodyViewModel.cs
> +            var currentDomain = this.SessionService.GetDomainOfExpertise(this.CurrentIteration);
The property CurrentDomain exists, use it instead

2023-04-18 11:54 UTC, antoineatrhea approved these changes

2023-04-20 07:16 UTC, jaimeatrhea approved these changes

2023-04-20 07:18 UTC, merged