Element scene properties update for CompoundParameterTypes : Fix #350
RHEAGROUP/COMET-WEB-Community-Edition pull request #356
Opened 2023-04-21 11:39 UTC by nabilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)
Fix #350 

The CompoundParameterType changes are not blocking the element scene update
### Description

2023-04-24 06:33 UTC, antoineatrhea requested changes

2023-04-24 06:33 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Viewer/PropertiesPanel/PropertiesComponentViewModel.cs
> +                    for(var componentIndex = 0; componentIndex < components.Count; componentIndex++)
Add a blank line

2023-04-24 06:33 UTC, antoineatrhea commented on COMETwebapp.Tests/Components/Viewer/PropertiesPanel/PropertiesComponentTestFixture.cs
> +            Assert.DoesNotThrowAsync(() => this.viewModel.ParameterValueSetChanged(parameterValueSet));
Please set does Assert inside an Assert.Multiple. Moreover, use the "Assert.That()"

2023-04-24 06:34 UTC, antoineatrhea commented
If possible, try to reach at least 70% coverage

2023-04-24 07:06 UTC, jaimeatrhea approved these changes
Approved when @antoineatrhea changes are fixed

2023-05-09 07:43 UTC, antoineatrhea approved these changes

2023-05-09 07:44 UTC, merged