[Model Editor] Draggable Element definitions : Fix #372 #373 #390 #393
RHEAGROUP/COMET-WEB-Community-Edition pull request #379
Opened 2023-05-19 15:31 UTC by nabilatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #372 #373 #390 #393

User can see all element definitions available in the model and drag and drop element usages
User can see element definition details by selecting a row
User can create a new ElementDefinition

![draggable-gif](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/assets/112706228/0d6681b2-0142-45be-9f72-72ceebf9ee1b)

![image](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/assets/112706228/2e1f1e42-6c81-4af4-8da6-8f9342e6a378)
![image](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/assets/112706228/781344cf-31b6-4e79-a0d4-365fb7574b02)

2023-05-22 07:02 UTC, antoineatrhea commented
Moreover, can you include JS scripts that you used into the wwwroot folder directly, under a js folder? So we don't rely on an hosted resource.

2023-05-31 07:31 UTC, jaimeatrhea requested changes

2023-06-01 09:54 UTC, nabilatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/Rows/ElementDefinitionRowViewModel.cs
> +        public ElementDefinitionRowViewModel()
This is used to create a copy of a ElementDefinitionRow so that we can drag a row from source to target

2023-06-02 10:03 UTC, antoineatrhea requested changes

2023-06-02 10:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs
> +        public ElementDefinitionTableViewModel(ISessionService sessionService, IDraggableElementService draggableElementService)
Global remark : Can you make the VM totally agnostic of JSInterop? Agreed to use a service, but remove that dependency and delegate that to the view if possible

2023-06-02 10:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs
> +        public void PopulateRows()
Missing documentation

2023-06-02 10:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs
> +    public class ElementDefinitionTableViewModel : DisposableObject, IElementDefinitionTableViewModel
Other general comment, can you try to reuse rows when possible? If the session is refresh or if you update things, don't delete and create everything. Check ParameterTableVM

2023-06-02 10:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/IElementDefinitionTableViewModel.cs
> +        Task LoadDotNetHelper(DotNetObjectReference<ElementDefinitionTable> dotNetHelper);
Missing return documentation

2023-06-02 10:03 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/IElementDefinitionTableViewModel.cs
> +        Task InitDraggableGrids(string firstGrid, string secondGrid);
Missing return documentation

2023-06-15 07:18 UTC, antoineatrhea requested changes

2023-06-15 07:18 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs
> +            this.Disposables.Add(observables.Merge().Subscribe(this.RecordChange));
Please replace that by InitializeSubscriptions(typeof(ElementBase))

2023-06-15 07:18 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/ModelEditor/ElementDefinitionTableViewModel.cs
> +        protected override void RecordChange(ObjectChangedEvent objectChangedEvent)
Please remove it since it is the exact same implementation has the base class

2023-06-16 09:40 UTC, antoineatrhea approved these changes

2023-08-04 07:02 UTC, lxatrhea approved these changes

2023-08-04 07:14 UTC, jaimeatrhea approved these changes

2023-08-04 08:27 UTC, merged