System representation use same tree in the 3DViewer : Fix #376
RHEAGROUP/COMET-WEB-Community-Edition pull request #387
Opened 2023-05-31 08:43 UTC by nabilatrhea

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fix #376 

Here we use the same ProductTree used in the 3DViewer

2023-05-31 09:58 UTC, antoineatrhea approved these changes
Small code style missing but functionality looks good

2023-05-31 09:58 UTC, antoineatrhea commented on COMETwebapp/ViewModels/Components/Viewer/Canvas/IProductTreeViewModel.cs
> +    using Microsoft.AspNetCore.Components;
Please add a break line

2023-05-31 09:58 UTC, antoineatrhea commented on COMETwebapp/Model/BaseNode.cs
> +}
Missing EOF

2023-05-31 12:10 UTC, jaimeatrhea requested changes

2023-05-31 12:10 UTC, jaimeatrhea commented on COMETwebapp/Components/Viewer/Canvas/NodeComponent.razor
I see that the way that I implemented this component can be improved. 

- Merge the if statements that can be merged to reduce the nesting.
- In order to select the correct image of the node (hide/show icons) the path can be computed, also the IsSceneObject can be computed. This will replace the lines of code 59-66.

2023-05-31 12:10 UTC, jaimeatrhea commented on COMETwebapp/ViewModels/Components/Viewer/Canvas/INodeComponentViewModel.cs
I think that this should also follow the same pattern. One type of VM for the ProductTree of the 3DViewer and another for the SystemRepresentation. You can make this class generic and rename it to be:
IBaseNodeViewModel<T> where T : BaseNode

This will help to remove all the casts that appear through the code

2023-06-09 09:31 UTC, jaimeatrhea commented
@nabilatrhea Gonna work on this to add the requested changes. I will open it again when it's done.

2023-06-16 11:52 UTC, antoineatrhea approved these changes

2023-06-16 11:54 UTC, merged