[Update] COMET to CDP4-COMET and update logo's; fixes #400
RHEAGROUP/COMET-WEB-Community-Edition pull request #401
Opened 2023-06-18 22:38 UTC by samatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
  - update logo in common and app
  - update COMET to CDP4-COMET

2023-06-18 23:02 UTC, nabilatrhea requested changes
Name also should be changed in styles.css file

2023-06-18 23:02 UTC, nabilatrhea commented on COMETwebapp/Components/Shared/About.razor
> +                <p>CDP4-COMET WEB Community Editition (CE) is the RHEA Group open source Concurrent Design web based application compliant with ECSS-E-TM-10-25 Annex A and Annex C</p>
small mistake (Editition) to Edition

2023-06-19 06:50 UTC, antoineatrhea approved these changes
When typo is fixed

2023-06-19 06:55 UTC, nabilatrhea approved these changes

2023-06-19 07:02 UTC, antoineatrhea commented
@samatrhea  can you also provide the favicon please?

2023-06-19 07:18 UTC, closed without merging