Fix code smells; Fix #395
RHEAGROUP/COMET-WEB-Community-Edition pull request #403
Opened 2023-06-19 10:38 UTC by jaimeatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
This PR fixes some code smells in the javascript files. It fixes #395 and it uses that logic in the ParameterEditorBodyViewModel

2023-06-26 08:09 UTC, antoineatrhea requested changes
Fix SonarQube please

2023-06-26 08:09 UTC, antoineatrhea commented on COMETwebapp/wwwroot/Scripts/babylonSpecifics.js
> -    let light1 = new BABYLON.HemisphericLight("HemisphericLight", new BABYLON.Vector3(2, 1, 0), scene);
This produce a bug detected by SonarQube, can you fix it please?

2023-06-26 08:12 UTC, nabilatrhea approved these changes
after fixing the detected Bug

2023-07-05 12:15 UTC, samatrhea approved these changes

2023-07-11 12:37 UTC, samatrhea commented
@jaimeatrhea any update on this?

2023-08-04 06:10 UTC, samatrhea commented
@jaimeatrhea any more work to be done on this?

2023-08-04 07:16 UTC, jaimeatrhea commented
@samatrhea No, unless the bug can de disabled from SonarQube

2023-08-16 07:14 UTC, antoineatrhea commented
@samatrhea I think that we should exclude _.js_ files from SonarQube checks. I'm afraid that resolving #420 will bring too many SonarQube issues.

2023-08-16 10:27 UTC, omaratrhea approved these changes

2023-08-16 12:34 UTC, samatrhea approved these changes

2023-08-16 12:35 UTC, merged