Improvements to the InputEditor
RHEAGROUP/COMET-WEB-Community-Edition pull request #462
Opened 2023-10-03 11:46 UTC by Robbware

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

The following changes will allow us to show/hide the Name and Short name fields on the InputEditor, via a configuration file. Additionally, a MultiComboBox component was created as DevExpress, by default, does not have a dropdown component which enables multiple choice.

2023-10-03 11:47 UTC, Robbware commented
Fixing the failing tests.

2023-10-03 12:18 UTC, jaimeatrhea reviewed
Some small requests

2023-10-03 12:18 UTC, jaimeatrhea commented on .gitignore
> +.idea/
Please add a new line at the end of the file

2023-10-03 12:18 UTC, jaimeatrhea commented on COMET.Web.Common/Components/MultiComboBox.razor.cs
> +//      Authors: Sam Gerené, Jaime Bernar
This component was copied from another project called AIDA. Please align the headers with the headers for the WebApp

2023-10-03 12:18 UTC, jaimeatrhea commented on COMET.Web.Common/Components/MultiComboBox.razor.css
This css file as is in the COMET.Web.Common is not going to be loaded. This styles need to be in the main app styles file (if they are already there just remove this file)

2023-10-03 15:30 UTC, samatrhea requested changes

2023-10-03 15:34 UTC, Robbware commented
Working on the coverage, just a bit more 😉

2023-10-04 09:15 UTC, samatrhea approved these changes

2023-10-04 09:16 UTC, jaimeatrhea approved these changes

2023-10-04 09:18 UTC, merged