Bug #181 (1067 - Gitlab): login bug
RHEAGROUP/COMET-WEB-Community-Edition pull request #467
Opened 2023-10-04 17:37 UTC by joao4all

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [ ] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fixed [#181](https://gitlab.innovetusa.com/comet/1067/-/issues/181) Gitlab bug

Solved problems with login page: now focused components will not show their error message. BindValueMode updated

2023-10-04 17:51 UTC, samatrhea approved these changes

2023-10-04 19:09 UTC, antoineatrhea requested changes
Small documentation missing. Could be nice to increase code coverage by testing cases on the Component

2023-10-05 06:32 UTC, antoineatrhea commented on COMET.Web.Common/Components/Login.razor
> +    <!-- <ValidationSummary/> -->
Remove this commented code please

2023-10-06 13:33 UTC, antoineatrhea requested changes

2023-10-06 13:33 UTC, antoineatrhea commented on COMET.Web.Common.Tests/Components/LoginTestFixture.cs
> +            Assert.IsFalse(renderer.Instance.FieldsFocusedStatus["UserName"]);
Please use Assert.That and surround the two Assert inside a Assert.Multiple( () => ... );

2023-10-06 13:33 UTC, antoineatrhea commented on COMET.Web.Common/Components/Login.razor.cs
> +        public Dictionary<string, bool> FieldsFocusedStatus
Can you remove the private property and just have the public ? and just put {get; private set;} ?

2023-10-10 06:41 UTC, antoineatrhea approved these changes

2023-10-10 09:17 UTC, merged