Unused elements dashboard; fixes 62
RHEAGROUP/COMET-WEB-Community-Edition pull request #65
Opened 2022-06-01 15:53 UTC by justineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Add unused and unreferenced elements dashboards.
+ Correct the error in option filter

2022-06-01 16:54 UTC, samatrhea requested changes

2022-06-01 16:54 UTC, samatrhea commented on COMETwebapp/IterationService/IterationService.cs
> +﻿namespace COMETwebapp.IterationService
- missing code header
  - there does not seem to be a unit test for this class, please add

2022-06-02 07:33 UTC, alexatrhea requested changes

2022-06-02 07:33 UTC, alexatrhea commented on COMETwebapp/Pages/ModelDashboard.razor
> +        <DxTabs @bind-ActiveTabIndex="@ActiveTabIndex">
I agree

2022-06-02 11:54 UTC, samatrhea requested changes

2022-06-02 11:54 UTC, samatrhea commented on COMETwebapp/Components/ModelDashboard/UnreferencedElements.razor
> +        IterationService iterationService = new IterationService(ISessionAnchor.OpenIteration);
convention is to use the `var` keyword, so please replace with:

`var iterationService = new IterationService(ISessionAnchor.OpenIteration);`

2022-06-02 11:54 UTC, samatrhea commented on COMETwebapp/Components/ModelDashboard/UnusedElements.razor
> +        IterationService iterationService = new IterationService(ISessionAnchor.OpenIteration);
convention is to use the `var` keyword, so please replace with:

`var iterationService = new IterationService(ISessionAnchor.OpenIteration);`

2022-06-02 11:54 UTC, samatrhea commented on COMETwebapp.Tests/IterationServiceTest/IterationServiceTest.cs
> +            Assert.IsNotEmpty(iterationService.GetParameterValueSets());
we typically make use of the `Assert.That` syntax, I think this then becomes:

`Assert.That(iterationService.GetParameterValueSets(), Is.Not.Empty);`

2022-06-02 13:07 UTC, samatrhea approved these changes

2022-06-02 13:10 UTC, closed without merging