Add manual refresh; fixes #57
RHEAGROUP/COMET-WEB-Community-Edition pull request #69
Opened 2022-06-08 13:27 UTC by justineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Add manual refresh in the application.
When the application is refreshing, each component listens to SessionEvent and re-renders with new values.

2022-06-09 09:45 UTC, samatrhea requested changes

2022-06-10 06:52 UTC, alexatrhea approved these changes
Aceepted pending Sam's comments.

2022-06-10 08:07 UTC, justineatrhea commented on COMETwebapp/Components/ModelDashboard/ParameterDashboard.razor
> +            this.StateHasChanged();
In the article, it is written : Blazor WebAssembly apps are single-threaded so do not have to account for thread safety.

2022-06-10 08:12 UTC, samatrhea approved these changes

2022-06-10 08:12 UTC, samatrhea commented on COMETwebapp/Components/ModelDashboard/ParameterDashboard.razor
> +            this.StateHasChanged();
then for webassembly its fine, but for server-side not. Something to consider when we switch to server-side

2022-06-10 08:45 UTC, closed without merging