Add switch domain feature; fixes #74
RHEAGROUP/COMET-WEB-Community-Edition pull request #75
Opened 2022-06-13 13:56 UTC by justineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
- Add feature to be able to switch domain in the application.
- Add correction in use of CDPMessageBus listeners => improve delays in session refresh

2022-06-13 14:32 UTC, samatrhea requested changes

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Components/ModelDashboard/ParameterDashboard.razor
> +        if (!Listeners.Keys.Contains("SessionEvent"))
please refactor using `TryGetValue`  method

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Components/ParameterTable.razor
> +        if (!Listeners.Keys.Contains("SessionEvent"))
please refactor using `TryGetValue` method

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Components/ParameterTable.razor
> +        var ListElements = ISessionAnchor.GetIteration()?.Element;
please rename the variable to `elementDefinitions`, no need to put the word `List` in the name of the variable

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor
> +        if (!Listeners.Keys.Contains("SessionEvent"))
please refactor using the `TryGetValue` method

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Pages/ModelDashboard/DataDetails.razor
> +            Listeners.Add("SessionEvent", CDPMessageBus.Current.Listen<SessionEvent>().Where(x => x.Status == SessionStatus.EndUpdate).Subscribe(x => {
please refactor using the `TryGetValue` method

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Pages/ModelDashboard/DataDetails.razor
> +        if (Criteria is not null && Domain is not null && iteration != null)
please prefix the local properties with the `this` keyword, e.g. `this.Criteria`

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Pages/ModelDashboard/ElementsDetails.razor
> +            Listeners.Add("SessionEvent", CDPMessageBus.Current.Listen<SessionEvent>().Where(x => x.Status == SessionStatus.EndUpdate).Subscribe(x =>
please refactor using the `TryGetValue` method

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Pages/ModelDashboard/ModelDashboard.razor
> +        if (!Listeners.Keys.Contains("Refreshing"))
please refactor using the `TryGetValue` method

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Shared/NavMenu.razor
> +    } else if (ISessionAnchor.IsSessionOpen && ISessionAnchor.GetIteration() != null)
please put the `else if` on a new line

2022-06-13 14:32 UTC, samatrhea commented on COMETwebapp/Shared/Header.razor
> +                this.StateHasChanged();
please replace this with `this.IsRefreshing = true;`

2022-06-13 15:43 UTC, samatrhea requested changes

2022-06-13 15:43 UTC, samatrhea commented on COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor
> +        this.ViewModelSubscribedParameters.Clear();
i would wrap these calls in a private `loadData` method (or a similar name like that`)

2022-06-13 15:43 UTC, samatrhea commented on COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor
> +        if (this.Listeners.TryGetValue("UpToDate", out var listener))
I think you need to reverse the logic here `if (!this.Listeners.TryGetValue("UpToDate", out var listener))`

2022-06-13 15:43 UTC, samatrhea commented on COMETwebapp/Components/SubscriptionDashboard/SubscribedTable.razor
> +                this.OnInitialized();
i would not call `this.OnInitialized();` here, refactor what you are doing in OnInitialized and call a new private method called something like `LoadData()`

2022-06-13 16:46 UTC, alexatrhea approved these changes
Approved pending Sam's comments.

2022-06-14 09:15 UTC, samatrhea approved these changes

2022-06-14 09:26 UTC, merged